[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_flags = 
    -D LV_CONF_INCLUDE_SIMPLE=1
    -I "${PROJECT_DIR}/include"
build_src_flags =
    -O0
    -g3
    -D SMARTKNOB_AUTOTEST=1
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200

; Add LVGL version 8.x
lib_deps =
    lvgl/lvgl@^8.4.0

